# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-11 13:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='headshot',
            field=models.ImageField(blank=True, default='defaule.jpg', null=True, upload_to='avatar/%Y/%m/%d', verbose_name='头像'),
        ),
        migrations.AlterField(
            model_name='user',
            name='signature',
            field=models.CharField(blank=True, default='这个家伙太懒了，什么都没留下来', max_length=128, null=True, verbose_name='个性签名'),
        ),
    ]
